import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { initConfig } from "@joyid/ckb";

const inter = Inter({ subsets: ["latin"] });

const JOY_ID_URL = "https://testnet.joyid.dev";
const JOY_ID_SERVER_URL = "https://api.joyid.dev";

initConfig({
  // your app name
  name: "Anmol NFT Minter demo",
  // your app logo
  logo: "https://fav.farm/🆔",
  // JoyID app url, optional
  joyidAppURL: JOY_ID_URL,
  // JoyID server url, optional
  joyidServerURL: JOY_ID_SERVER_URL,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
